function(write_commit_hook)
  if (EXISTS ${CMAKE_SOURCE_DIR}/.git/hooks)
    configure_file(${CMAKE_SOURCE_DIR}/CMake/pre-commit.sh ${CMAKE_SOURCE_DIR}/.git/hooks/pre-commit @ONLY)
    file(CHMOD ${CMAKE_SOURCE_DIR}/.git/hooks/pre-commit PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
  endif ()
endfunction()
