name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    env:
      BUILD_TYPE: Debug
      CMAKE_COLOR_DIAGNOSTICS: ON
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo --preserve-env=GITHUB_JOB .github/scripts/deps.sh
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEST_MODE=ON -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j$(nproc)
      - name: Test MemCheck
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure --test-action memcheck --output-junit junit.xml
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure --output-junit junit.xml
      - name: Generate Coverage
        working-directory: ${{github.workspace}}/build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target coverage
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-test
          path: |
            build/Testing
            build/CMakeFiles
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{github.workspace}}/build/coverage
      - name: Junit Test Dashboard
        if: always()
        uses: janisz/action@v2
        with:
          paths: ${{github.workspace}}/build/junit.xml
      - name: Code Coverage Summary Report
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage.xml
          format: markdown
          output: both
      - name: Coverage Summary
        if: always()
        run: cat ${{github.workspace}}/code-coverage-results.md >> $GITHUB_STEP_SUMMARY
  build:
    name: Build
    env:
      BUILD_TYPE: Debug
      CMAKE_COLOR_DIAGNOSTICS: ON
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: [ aarch64, x86_64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo --preserve-env=GITHUB_JOB .github/scripts/deps.sh
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DARCH=${{matrix.arch}} -DCMAKE_VERBOSE_MAKEFILE=ON -G Ninja
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j$(nproc)
      - name: Build Image
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target image -- -j$(nproc)
      - name: Build OVMF
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ovmf -- -j$(nproc)
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure --output-junit junit.xml
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{matrix.arch}}
          path: |
            build/Testing
            build/CMakeFiles
            build/kernel/kernel
      - name: Junit Test Dashboard
        if: always()
        uses: janisz/action@v2
        with:
          paths: ${{github.workspace}}/build/junit.xml
      - name: Add output to summary
        if: always()
        run: |
          file ${{github.workspace}}/build/kernel/kernel >> $GITHUB_STEP_SUMMARY
